### PR TITLE
Add `set_prefer_alonzo_format` to `AuxiliaryData`

### PR DESCRIPTION
**Pull request by MitchyCola**
Added `set_prefer_alonzo_format` function to `AuxiliaryData` impl in `metadata.rs`. This will be used to change `prefer_alonzo_format` in WASM.

### CODE REVIEW

**Review by lisicky — COMMENTED** [review]
/check

**Review by lisicky — APPROVED** [review]
Thanks @MitchyCola !

**Review by lisicky — COMMENTED** [review]
/check

**Review by twwu123 — APPROVED** [review]

**Review by lisicky — COMMENTED** [review]
/check

**Pull request merged**
