### PR TITLE
Release / 10.1.0

### PR DESCRIPTION
**Pull request by vsubhuman**
Milestone: https://github.com/Emurgo/cardano-serialization-lib/milestone/11?closed=1

## Change Set

- [x] https://github.com/Emurgo/cardano-serialization-lib/pull/367 [@rooooooooob]
- [x] https://github.com/Emurgo/cardano-serialization-lib/pull/374 [@vsubhuman]
- [x] https://github.com/Emurgo/cardano-serialization-lib/pull/392 [@rooooooooob]
- [x] https://github.com/Emurgo/cardano-serialization-lib/pull/409 [@ozgrakkurt]
- [x] https://github.com/Emurgo/cardano-serialization-lib/pull/430 [@lisicky]
- [x] https://github.com/Emurgo/cardano-serialization-lib/pull/436 [@vsubhuman]

### CODE REVIEW

**Review by vsubhuman — COMMENTED** [review]
/check

**Comment by vsubhuman** [comment]
Release: https://github.com/Emurgo/cardano-serialization-lib/releases/tag/10.1.0

**Comment by vsubhuman** [comment]
Published:
- https://www.npmjs.com/package/@emurgo/cardano-serialization-lib-nodejs/v/10.1.0
- https://www.npmjs.com/package/@emurgo/cardano-serialization-lib-browser/v/10.1.0
- https://www.npmjs.com/package/@emurgo/cardano-serialization-lib-asmjs/v/10.1.0
- https://crates.io/crates/cardano-serialization-lib/10.1.0

**Comment by NicolasDP** [comment]
since #436 is a breaking change you should have changed the major version and not the minor version:

> MINOR version when you add functionality in a backwards compatible manner

https://semver.org

Now you are not forced to respect this. but then I am curious what version policy you follow ?

**Comment by vsubhuman** [comment]
> but then I am curious what version policy you follow ?

Mandatory major version change when **JS** API is breaking in a non-compatible way

**Pull request merged**
