### PR TITLE
Fixing GH-checks to run the build properly + Fixing `rand` dependency wasm support

### PR DESCRIPTION
**Pull request by vsubhuman**

### CODE REVIEW

**Review by vsubhuman — COMMENTED** [review]
/check

**Review by vsubhuman — COMMENTED** [review]
/check

**Review by vsubhuman — COMMENTED** [review]
/check

**Comment by vsubhuman** [comment]
After adding the `rand` dependency in https://github.com/Emurgo/cardano-serialization-lib/pull/232 the wasm build started failing with: `error: the wasm32-unknown-unknown target is not supported by default, you may need to enable the "js" feature. For more information see: https://docs.rs/getrandom/#webassembly-support`

image

In **this** PR the gh-checks are fixed to properly run the builds and the build scripts are fixed to properly return the exit status for the checks can fail.

To fix the problem with the `rand` crate I have to add additional explicit dependency:
```
getrandom = { version = "0.2.3", features = ["js"] }
```

**Review by vsubhuman — COMMENTED** [review]
/check

**Review by pedromtcosta — APPROVED** [review]
Looks good! Tested the build locally as well 👍

**Pull request merged**
