### PR TITLE
Fix dependency issues 

### PR DESCRIPTION
**Pull request by trevor-crypto**
1. Reorganize dependencies and remove requirements ("=") on wasm-bindgen
   and js-sys, due to conflicts that can occur when using this crate.
2. Replace wasm-bindgen's "serde-serialize" feature with
   serde-wasm-bindgen due to cyclical dependency issue.

Relates to:
https://github.com/tkaitchuck/aHash/issues/95
https://github.com/rustwasm/wasm-bindgen/pull/3031

### CODE REVIEW

**Review by lisicky — APPROVED** [review]
/check

**Comment by lisicky** [comment]
@trevor-crypto perfect PR, thanks!

**Comment by trevor-crypto** [comment]
@lisicky thank you for reviewing. It appears that the failing check is warning that a `pub(crate)` function is unused. It is used only in a test. Should I add the `#[cfg(test)]` on it, or just leave it?

**Comment by lisicky** [comment]
Thanks @trevor-crypto :) This is our problem, don't worry we will fix it.

**Review by vsubhuman — APPROVED** [review]
Thank you, @trevor-crypto !

**Pull request merged**
