### PR TITLE
Update min_ada_required() to Alonzo rules

### PR DESCRIPTION
**Pull request by rooooooooob**
Following: https://github.com/input-output-hk/cardano-ledger-specs/blob/master/doc/explanations/min-utxo-alonzo.rst

Some tests in tx_builder.rs still need to be updated

### CODE REVIEW

**Comment by vsubhuman** [comment]
Thank you, @rooooooooob! This is a great change, but it's really breaking tho, so it gonna need to be in the next version `10.0.0`

**Review by pedromtcosta — APPROVED** [review]
Looks good!

**Review by vsubhuman — APPROVED** [review]

**Review by vsubhuman — COMMENTED** [review]
/check

**Comment by vsubhuman** [comment]
Changed target to another local branch `alonzo-min-utxo-size` to resolve conflicts and run tests first

**Pull request merged**
